export default [
    {
        name:'资讯管理',
        icon:'file-sync',
        path:'',
        id:'0',
        children:[
            {
                name:'资讯管理',
                icon:'',
                path:'/admin/information',
            }
        ]
    },
    {
        name:'图片管理',
        icon:'file-sync',
        path:'',
        id:'1',
        children:[
            {
                name:'图片管理',
                icon:'',
                path:'/admin/photos',
            }
        ]
    },
    {
        name:'产品管理',
        icon:'file-sync',
        path:'',
        id:'1',
        children:[
            {
                name:'品牌管理',
                icon:'',
                path:'/admin/products/brand'
            },
            {
                name:'分类管理',
                icon:'',
                path:'/admin/products/classification'
            },
            {
                name:'产品管理',
                icon:'',
                path:'/admin/products'
            }

        ]
    },
    {
        name:'评论管理',
        icon:'file-sync',
        path:'',
        id:'1',
        children:[
            {
                name:'评论列表',
                icon:'',
                path:'/admin/comment/commentList',
            },
            {
                name:'意见反馈',
                icon:'',
                path:'/admin/comment/idea',
            },
        ]
    },
    {
        name:'会员管理',
        icon:'file-sync',
        path:'',
        id:'1',
        children:[
            {
                name:'会员列表',
                icon:'',
                path:'/admin/member/memberList',
            },
            {
                name:'删除的会员',
                icon:'',
                path:'/admin/member/memberDel',
            },
            {
                name:'等级管理 ',
                icon:'',
                path:'/admin/member/rank',
            },
            {
                name:'积分管理',
                icon:'',
                path:'/admin/member/integral',
            },
            {
                name:'浏览记录',
                icon:'',
                path:'/admin/member/records',
            },
            {
                name:'下载记录',
                icon:'',
                path:'/admin/member/down',
            },
            {
                name:'分享记录',
                icon:'',
                path:'/admin/member/share',
            },
        ]
    },
    {
        name:'管理员管理',
        icon:'file-sync',
        path:'',
        id:'1',
        children:[
            {
                name:'角色列表',
                icon:'',
                path:'/admin/admnistrators/role'
            },
            {
                name:'权限反馈',
                icon:'',
                path:'/admin/admnistrators/limit'
            },
            {
                name:'管理员',
                icon:'',
                path:'/admin/admnistrators'
            },
        ]
    },
    {
        name:'系统统计',
        icon:'file-sync',
        path:'',
        id:'1',
        children:[
            {
                name:'折线图',
                icon:'',
                path:'/admin/system/lineChart'
            },
            {
                name:'时间轴折线图',
                icon:'',
                path:'/admin/system/timelineChart'
            },
            {
                name:'区域图',
                icon:'',
                path:'/admin/system/areaChart'
            },
            {
                name:'柱状图',
                icon:'',
                path:'/admin/system/columnChart'
            },
            {
                name:'饼状图',
                icon:'',
                path:'/admin/system/PancakeChart'
            },
            {
                name:'3D柱状图',
                icon:'',
                path:'/admin/system/3DColumnChart'
            },
            {
                name:'3D饼状图',
                icon:'',
                path:'/admin/system/3DPancakeChart'
            },
        ]
    },
    {
        name:'系统管理',
        icon:'file-sync',
        path:'/admin/systemManage',
        id:'1',
        children:[
            {
                name:'系统设置',
                icon:'',
                path:'/admin/systemManage/setting'
            },
            {
                name:'栏目管理',
                icon:'',
                path:'/admin/systemManage/column'
            },
            {
                name:'数据字典',
                icon:'',
                path:'/admin/systemManage/data'
            },
            {
                name:'屏蔽词',
                icon:'',
                path:'/admin/systemManage/shield'
            },
            {
                name:'系统日志',
                icon:'',
                path:'/admin/systemManage/journal'
            }
        ]
    }
]